<?php

//! Loads the view that allows users to add/remove the current product from various categories. Should be called by CategoriesView
class CategorySelectorView extends View {

	//! Obj:CatalogueModel - the catalogue from which to draw the categories from
	var $mCatalogue;
	//! String - the element (generally a DIV) that the output of this view shoudl be written to
	var $mTargetElement;
	//! String - Used to differentiate different instances of this view within the same page/form
	var $mPrefix;
	//! Obj:ProductModel - The product that is currently being edited
	// This is needed to 'check' the correct box when displaying the list of categories
	var $mProduct;

	//! Generic load function
	/*!
	 * @param [in] catalogueId : Int			- The catalogue used to populate the categories
	 * @param [in] targetElement : String		- The (ID of the) element (generally a DIV) to write the output (product displays) to
	 * @param [in] prefix : String				- Used to differentiate different instances of this view within the same page/form
	 * @return String - The code for the view
	 */
	function LoadDefault($catalogueId, $targetElement, $prefix, $product) {
		$this->mCatalogue = new CatalogueModel ( $catalogueId );
		$this->mTargetElement = $targetElement;
		$this->mPrefix = $prefix;
		$this->mProduct = $product;

		$this->IncludeJavascript ( 'RequestHandler.js' );
		$this->IncludeJavascript ( 'ResponseHandler.js' );
		$this->IncludeJavascript ( 'CategorySelectorHandler.js' );
	//	$this->IncludeCss ( 'CategorySelectorFinder.css.php' );

		$this->InitialiseDisplay ();
		$this->LoadTopLevelCategories ();
		$this->LoadSubCategories ();
		$this->CloseDisplay ();
		return $this->mPage;
	}

	//! Adds heading and opens a DIV with id CategorySelectorViewContainer
	function InitialiseDisplay() {
		$this->mPage .= '<div id="' . $this->mPrefix . 'CategorySelectorViewContainer" class="categorySelectorViewContainer">';
	}

	//! Closes the CategorySelectorViewContainer DIV (assuming that all DIVs in between are well formed)
	function CloseDisplay() {
		$this->mPage .= '</div>';
	}

	//! Loads the top level categories in the correct catalogue
	// This is the only part of the CategorySelectorView that is generated by PHP; the rest is done in CategorySelectorHandler.js using the output of CategorySelectorAjaxHandler.php
	function LoadTopLevelCategories() {
		$registry = Registry::GetInstance ();
		$categoryController = new CategoryController ( );
		$allCategories = $categoryController->GetAllTopLevelCategoriesForCatalogue ( $this->mCatalogue );
		$this->mPage .= '<div id="' . $this->mPrefix . 'topLevelCategoryContainer" class="topLevelCategoryContainer">';
		foreach ( $allCategories as $category ) {
			if ($category->Contains ( $this->mProduct )) {
				$checked = "checked";
			} else {
				$checked = "";
			}
			$this->mPage .= <<<EOT
<div class="categorySelectorViewMenuItem" id="{$this->mPrefix}topLevelCategory{$category->GetCategoryId()}" name="{$this->mPrefix}topLevelCategory">
	<input	type="checkbox" name="{$this->mPrefix}topLevelCheckbox{$category->GetCategoryId()}" id="{$this->mPrefix}topLevelCheckbox{$category->GetCategoryId()}"
			style="width: auto; margin-left: -4px; margin-right: 4px;"
			onClick="MakeRequest('{$registry->AjaxHandlerDir}/CategorySelectorAjaxHandler.php?addTopLevelCategory={$category->GetCategoryId()}&targetElement={$this->mTargetElement}&prefix={$this->mPrefix}');"
			{$checked} />
		<a href="#" onClick="MakeRequest('{$registry->AjaxHandlerDir}/CategorySelectorAjaxHandler.php?openTopLevelCategory={$category->GetCategoryId()}&targetElement={$this->mTargetElement}&prefix={$this->mPrefix}'); FocusTopLevel('{$category->GetCategoryId()}')">
			{$category->GetDisplayName()}
		</a>
</div>
EOT;
		}
		$this->mPage .= '</div>';
	}

	//! Loads the container for the sub categories, assuming it will be filled by the Javascript part of the view
	function LoadSubCategories() {
		$this->mPage .= '<div id="' . $this->mPrefix . 'subLevelCategoryContainer" class="subLevelCategoryContainer"></div>';
	}

}

?>