<?php

//! Simulates the Mac "Finder" interface
class MacFinderView extends View {

	//! Obj:CatalogueModel : Catalogue for which to display the interface
	var $mCatalogue;
	//! String : MacFinderView requires an element (generally a DIV) to "spit" the products out into \todo{Maybe make this optional?}
	var $mTargetElement;
	//! String : To make the form fields unique, a prefix is added to each field to avoid conflicts (Can be anything, eg. UPGRADES might be a good choice for the upgrades section...)
	var $mPrefix;
	//! The style of the output, optional
	var $mStyle;

	//! Generic load function
	/*!
	 * @param [in] catalogueId : Int			- The catalogue used to populate the categories
	 * @param [in] targetElement : String		- The (ID of the) element (generally a DIV) to write the output (product displays) to
	 * @param [in] prefix : String				- Used to differentiate different instances of this view within the same page/form
	 * @param [in] style : String	 			- Used to decide the output style of the products. Options=default/orderForm, optional
	 * @return String - The code for the view
	 */
	function LoadDefault($catalogueId, $targetElement, $prefix, $style = 'default', $secure = false) {
		$this->mCatalogue = new CatalogueModel ( $catalogueId );
		$this->mSystemSettings = new SystemSettingsModel($this->mCatalogue);
		$this->mTargetElement = $targetElement;
		$this->mStyle = $style;
		$this->mPrefix = $prefix;
		$this->mSecure = $secure;
		if ($this->mSecure) {
			$this->IncludeJavascript ( 'RequestHandler.js', true, true );
			$this->IncludeJavascript ( 'ResponseHandler.js', true, true );
			$this->IncludeJavascript ( 'MacViewHandler.js', true, true );
			$this->IncludeCss ( 'MacFinder.css.php', true, false, true );
		} else {
			$this->IncludeJavascript ( 'RequestHandler.js' );
			$this->IncludeJavascript ( 'ResponseHandler.js' );
			$this->IncludeJavascript ( 'MacViewHandler.js' );
			$this->IncludeCss ( 'MacFinder.css.php' );
		}
		$this->InitialiseDisplay ();
		$this->LoadTopLevelCategories ();
		$this->LoadSubCategories ();
		$this->LoadProducts ();
		$this->CloseDisplay ();
		return $this->mPage;
	}

	//! Initialises the mac view container
	function InitialiseDisplay() {
		$this->mPage .= '<div id="' . $this->mPrefix . 'macViewContainer" class="macViewContainer">';
	}

	//! Closes the display
	function CloseDisplay() {
		$this->mPage .= '</div>';
	}

	//! Loads the top level categories in the correct catalogue
	// This is the only part of the MacView that is generated by PHP; the rest is done in MacViewHandler.js using the output of MacFinderAjaxHandler.php
	function LoadTopLevelCategories() {
		$registry = Registry::GetInstance ();
		if ($this->mSecure) {
			$ajaxDir = str_replace ( 'http', 'https', $registry->AjaxHandlerDir );
		} else {
			$ajaxDir = $registry->AjaxHandlerDir;
		}
		$categoryController = new CategoryController ( );
		$this->mPage .= '<div id="' . $this->mPrefix . 'topLevelCategoryContainer" class="topLevelCategoryContainer">'; // Change this class to the package icon
		// ***** Packages
		if ($this->mSystemSettings->GetShowPackages()) {
			$this->mPage .= '<div class="macViewMenuItemPackages" id="packages" name="packages">';
			$this->mPage .= '<a href="#" onClick="MakeRequest(\'' . $ajaxDir . '/MacFinderAjaxHandler.php?topLevelPackages=' . $this->mCatalogue->GetCatalogueId () . '&targetElement=' . $this->mTargetElement . '&prefix=' . $this->mPrefix . '&style=' . $this->mStyle . '&catalogue=' . $this->mCatalogue->GetCatalogueId () . '\'); FocusTopLevel(\'packages\')">Packages</a>';
			$this->mPage .= '</div>';
		}
		// ***** Products
		$allCategories = $categoryController->GetAllTopLevelCategoriesForCatalogue ( $this->mCatalogue );
		foreach ( $allCategories as $category ) {
			$this->mPage .= '<div class="macViewMenuItem"
									id="' . $this->mPrefix . 'topLevelCategory' . $category->GetCategoryId () . '"
									name="' . $this->mPrefix . 'topLevelCategory' . $category->GetCategoryId () . '"
									>';
			$this->mPage .= '<a href="#" onClick="MakeRequest(\'' . $ajaxDir . '/MacFinderAjaxHandler.php?topLevelCategory=' . $category->GetCategoryId () . '&targetElement=' . $this->mTargetElement . '&prefix=' . $this->mPrefix . '&style=' . $this->mStyle . '\'); FocusTopLevel(\'' . $category->GetCategoryId () . '\')">' . $category->GetDisplayName () . '</a>';
			$this->mPage .= '</div>';
		}
		$this->mPage .= '</div>';
	}

	//! Loads the container for the sub categories, assuming it will be filled by the Javascript part of the view
	function LoadSubCategories() {
		$this->mPage .= '<div id="' . $this->mPrefix . 'subLevelCategoryContainer" class="subLevelCategoryContainer"></div>';
	}

	//! Loads the container for the products, assuming it will be filled by the Javascript part of the view
	function LoadProducts() {
		$this->mPage .= '<div id="' . $this->mPrefix . 'productLevelCategoryContainer" class="productLevelCategoryContainer"></div>';
	}
}

?>